/**
 * Mock Data Store for Exam Portal
 * Pre-populated demo data for Student, Interviewer, and Admin workflows.
 */

export const DEMO_USERS = {
  student: {
    id: 'std_01',
    name: 'Aarav Sharma',
    email: 'student@examportal.edu',
    role: 'student',
    rollNo: 'CS2026-089',
    department: 'Computer Science & Engineering',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  },
  interviewer: {
    id: 'int_01',
    name: 'Dr. Priya Ramesh',
    email: 'interviewer@examportal.edu',
    role: 'interviewer',
    domain: 'Artificial Intelligence & Data Science',
    experience: '8 Years',
    department: 'Department of AI & Data Science',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
  },
  admin: {
    id: 'adm_01',
    name: 'University Super Admin',
    username: 'admin',
    email: 'admin@examportal.edu',
    role: 'admin',
    department: 'Central Examination Board',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
  },
};

export const MOCK_UPCOMING_INTERVIEWS = [
  {
    id: 'int_101',
    company: 'TechCorp University Exam',
    domain: 'Data Structures & Algorithms',
    date: '2026-08-10',
    time: '10:00 AM IST',
    duration: '45 Mins',
    totalQuestions: 15,
    status: 'Ready',
    instructions: 'Ensure camera and microphone are connected. No tab switching allowed during test.',
    code: 'DSA-CS301',
  },
  {
    id: 'int_102',
    company: 'Alpha AI Systems',
    domain: 'Machine Learning & Python',
    date: '2026-08-12',
    time: '02:00 PM IST',
    duration: '60 Mins',
    totalQuestions: 20,
    status: 'Scheduled',
    instructions: 'AI Proctoring will monitor multi-person, face angle, and tab switching events.',
    code: 'ML-AI402',
  },
  {
    id: 'int_103',
    company: 'CloudWorks Tech',
    domain: 'Database Management Systems',
    date: '2026-08-15',
    time: '11:30 AM IST',
    duration: '30 Mins',
    totalQuestions: 15,
    status: 'Scheduled',
    instructions: 'SQL queries, index optimization, and normalization concepts.',
    code: 'DBMS-204',
  },
  {
    id: 'int_104',
    company: 'CyberShield University',
    domain: 'Network Security & Encryption',
    date: '2026-08-18',
    time: '04:00 PM IST',
    duration: '45 Mins',
    totalQuestions: 15,
    status: 'Scheduled',
    instructions: 'Full lock-down browser rules strictly enforced.',
    code: 'NS-CS501',
  },
];

export const MOCK_COMPLETED_INTERVIEWS = [
  {
    id: 'comp_201',
    company: 'Global Software Inc',
    domain: 'Full Stack Web Development',
    date: '2026-08-02',
    time: '02:00 PM',
    marks: 92,
    totalMarks: 100,
    rank: 1,
    percentage: 92,
    status: 'Passed - Distinction',
    proctoringScore: '99% Clean',
    violationsCount: 0,
    timeTaken: '34 Mins',
  },
  {
    id: 'comp_202',
    company: 'Apex Systems',
    domain: 'Operating Systems & Linux',
    date: '2026-07-28',
    time: '11:00 AM',
    marks: 84,
    totalMarks: 100,
    rank: 3,
    percentage: 84,
    status: 'Passed',
    proctoringScore: '96% Clean',
    violationsCount: 1,
    timeTaken: '40 Mins',
  },
  {
    id: 'comp_203',
    company: 'DataViz AI',
    domain: 'Object Oriented Programming',
    date: '2026-07-20',
    time: '10:00 AM',
    marks: 78,
    totalMarks: 100,
    rank: 8,
    percentage: 78,
    status: 'Passed',
    proctoringScore: '94% Clean',
    violationsCount: 2,
    timeTaken: '28 Mins',
  },
  {
    id: 'comp_204',
    company: 'InfraCloud University',
    domain: 'Computer Networks',
    date: '2026-07-15',
    time: '03:00 PM',
    marks: 88,
    totalMarks: 100,
    rank: 2,
    percentage: 88,
    status: 'Passed - High Honors',
    proctoringScore: '100% Clean',
    violationsCount: 0,
    timeTaken: '38 Mins',
  },
];

export const MOCK_MCQ_QUESTIONS = [
  {
    id: 1,
    question: 'In a Binary Search Tree (BST), what is the worst-case time complexity of searching an element?',
    options: ['O(1)', 'O(log N)', 'O(N)', 'O(N log N)'],
    correctAnswer: 2,
    explanation: 'In a skewed or degenerate binary search tree, all elements are in a single linear path, leading to O(N) worst-case time complexity.',
  },
  {
    id: 2,
    question: 'Which HTTP method should be idempotent according to REST architectural constraints?',
    options: ['POST and DELETE', 'GET, PUT, and DELETE', 'POST and PATCH', 'PUT and POST'],
    correctAnswer: 1,
    explanation: 'GET, PUT, and DELETE are idempotent because multiple identical requests will produce the same server state as a single request.',
  },
  {
    id: 3,
    question: 'What is the primary function of the Virtual DOM in modern frontend frameworks like React?',
    options: [
      'Directly manipulate the browser DOM hardware pixels',
      'Maintain an in-memory light copy of the DOM to minimize expensive actual DOM re-renders',
      'Automatically compile CSS code into web assembly',
      'Handle database connections on the browser client',
    ],
    correctAnswer: 1,
    explanation: 'The Virtual DOM computes minimum DOM diffing updates in memory before applying reconciled batch updates to the real browser DOM.',
  },
  {
    id: 4,
    question: 'In Operating Systems, what problem occurs when two or more processes are waiting infinitely for resources held by each other?',
    options: ['Thrashing', 'Starvation', 'Deadlock', 'Paging fault'],
    correctAnswer: 2,
    explanation: 'Deadlock occurs when processes hold resources while waiting for other resources locked by waiting processes in a circular wait dependency.',
  },
  {
    id: 5,
    question: 'Which of the following sorting algorithms guarantees O(N log N) time complexity in all cases (Best, Average, Worst)?',
    options: ['Quick Sort', 'Bubble Sort', 'Merge Sort', 'Insertion Sort'],
    correctAnswer: 2,
    explanation: 'Merge Sort consistently divides arrays into halves and merges them, maintaining O(N log N) in best, average, and worst scenarios.',
  },
  {
    id: 6,
    question: 'In SQL databases, what does the ACID property "Isolation" ensure?',
    options: [
      'Data is immediately replicated to backup servers',
      'Transactions execute independently without interfering with concurrent transactions',
      'Data types strictly match column definitions',
      'Queries automatically cache results',
    ],
    correctAnswer: 1,
    explanation: 'Isolation ensures that concurrent execution of transactions leaves the database in the same state as if transactions were executed sequentially.',
  },
  {
    id: 7,
    question: 'What is the primary advantage of Convolutional Neural Networks (CNNs) in Computer Vision tasks?',
    options: [
      'They do not require matrix multiplication',
      'They exploit spatial locality using shared weights and local receptive fields',
      'They operate without activation functions',
      'They process sequential text faster than Recurrent networks',
    ],
    correctAnswer: 1,
    explanation: 'CNNs preserve feature spatial hierarchy using weight sharing and local convolutional kernel sliding windows.',
  },
  {
    id: 8,
    question: 'In TCP/IP networking, which protocol operates at the Transport Layer and provides reliable, connection-oriented data transfer?',
    options: ['UDP', 'IP', 'TCP', 'ICMP'],
    correctAnswer: 2,
    explanation: 'TCP (Transmission Control Protocol) is connection-oriented, offering sequence numbering, error checking, and flow control.',
  },
  {
    id: 9,
    question: 'What is the time complexity of looking up a key in an ideal Hash Table with zero collisions?',
    options: ['O(1)', 'O(log N)', 'O(N)', 'O(N^2)'],
    correctAnswer: 0,
    explanation: 'Direct index computation via a hash function gives O(1) constant time access in an ideal hash table without collisions.',
  },
  {
    id: 10,
    question: 'In Object-Oriented Programming, what principle states that derived classes must be substitutable for their base classes without altering program correctness?',
    options: [
      'Single Responsibility Principle',
      'Liskov Substitution Principle',
      'Interface Segregation Principle',
      'Dependency Inversion Principle',
    ],
    correctAnswer: 1,
    explanation: 'The Liskov Substitution Principle (L in SOLID) demands that subtype objects can replace supertype objects without breaking functionality.',
  },
];

export const MOCK_CANDIDATES = [
  {
    id: 'cand_1',
    name: 'Ananya Roy',
    email: 'ananya.roy@university.edu',
    rollNo: 'CS2026-012',
    domain: 'Data Structures & Algorithms',
    score: 96,
    status: 'Completed',
    proctoringFlag: 'Clean',
    violationsCount: 0,
    date: '2026-08-07',
  },
  {
    id: 'cand_2',
    name: 'Rohan Mehta',
    email: 'rohan.m@university.edu',
    rollNo: 'CS2026-045',
    domain: 'Data Structures & Algorithms',
    score: 88,
    status: 'Completed',
    proctoringFlag: 'Clean',
    violationsCount: 0,
    date: '2026-08-07',
  },
  {
    id: 'cand_3',
    name: 'Sneha Patel',
    email: 'sneha.p@university.edu',
    rollNo: 'AI2026-088',
    domain: 'Machine Learning',
    score: 84,
    status: 'Completed',
    proctoringFlag: 'Minor Flag (1 Tab Switch)',
    violationsCount: 1,
    date: '2026-08-06',
  },
  {
    id: 'cand_4',
    name: 'Vikram Singh',
    email: 'vikram.s@university.edu',
    rollNo: 'CS2026-102',
    domain: 'Database Systems',
    score: 72,
    status: 'Completed',
    proctoringFlag: 'Multiple Person Alert',
    violationsCount: 3,
    date: '2026-08-05',
  },
  {
    id: 'cand_5',
    name: 'Kavya Nair',
    email: 'kavya.n@university.edu',
    rollNo: 'AI2026-019',
    domain: 'Machine Learning',
    score: 91,
    status: 'Completed',
    proctoringFlag: 'Clean',
    violationsCount: 0,
    date: '2026-08-05',
  },
];

export const MOCK_PAST_INTERVIEWS_INTERVIEWER = [
  {
    id: 'pi_01',
    name: 'DSA Mid-Semester Final Exam',
    date: '2026-08-05',
    noOfStudents: 128,
    averageScore: 82.4,
    domain: 'Data Structures',
    passPercentage: '94%',
  },
  {
    id: 'pi_02',
    name: 'Machine Learning & Neural Nets Placement Test',
    date: '2026-07-28',
    noOfStudents: 94,
    averageScore: 78.9,
    domain: 'AI & Data Science',
    passPercentage: '88%',
  },
  {
    id: 'pi_03',
    name: 'DBMS Schema & SQL Optimization Quiz',
    date: '2026-07-18',
    noOfStudents: 156,
    averageScore: 85.1,
    domain: 'Database Systems',
    passPercentage: '96%',
  },
  {
    id: 'pi_04',
    name: 'Web Engineering & Security Exam',
    date: '2026-07-10',
    noOfStudents: 110,
    averageScore: 79.5,
    domain: 'Web Architecture',
    passPercentage: '91%',
  },
];

export const MOCK_LEADERBOARD = [
  { rank: 1, studentName: 'Ananya Roy', marks: 96, percentage: '96%', status: 'Distinction', rollNo: 'CS2026-012', department: 'CSE' },
  { rank: 2, studentName: 'Aarav Sharma', marks: 92, percentage: '92%', status: 'Distinction', rollNo: 'CS2026-089', department: 'CSE' },
  { rank: 3, studentName: 'Kavya Nair', marks: 91, percentage: '91%', status: 'Distinction', rollNo: 'AI2026-019', department: 'AI & DS' },
  { rank: 4, studentName: 'Rohan Mehta', marks: 88, percentage: '88%', status: 'Passed', rollNo: 'CS2026-045', department: 'CSE' },
  { rank: 5, studentName: 'Sneha Patel', marks: 84, percentage: '84%', status: 'Passed', rollNo: 'AI2026-088', department: 'AI & DS' },
  { rank: 6, studentName: 'Aditya Varma', marks: 82, percentage: '82%', status: 'Passed', rollNo: 'ECE2026-033', department: 'ECE' },
  { rank: 7, studentName: 'Meera Iyer', marks: 80, percentage: '80%', status: 'Passed', rollNo: 'IT2026-007', department: 'IT' },
  { rank: 8, studentName: 'Vikram Singh', marks: 72, percentage: '72%', status: 'Passed', rollNo: 'CS2026-102', department: 'CSE' },
];

export const MOCK_ADMIN_STUDENTS = [
  { id: 'st_1', name: 'Aarav Sharma', email: 'student@examportal.edu', department: 'Computer Science', status: 'Active', examsTaken: 4, avgScore: '88%' },
  { id: 'st_2', name: 'Ananya Roy', email: 'ananya.roy@university.edu', department: 'Computer Science', status: 'Active', examsTaken: 6, avgScore: '94%' },
  { id: 'st_3', name: 'Kavya Nair', email: 'kavya.n@university.edu', department: 'AI & Data Science', status: 'Active', examsTaken: 5, avgScore: '90%' },
  { id: 'st_4', name: 'Rohan Mehta', email: 'rohan.m@university.edu', department: 'Information Tech', status: 'Active', examsTaken: 3, avgScore: '82%' },
  { id: 'st_5', name: 'Siddharth Rao', email: 'siddharth.r@university.edu', department: 'Electronics', status: 'Suspended', examsTaken: 2, avgScore: '45%' },
  { id: 'st_6', name: 'Pooja Hegde', email: 'pooja.h@university.edu', department: 'Computer Science', status: 'Active', examsTaken: 4, avgScore: '86%' },
];

export const MOCK_ADMIN_INTERVIEWERS = [
  { id: 'int_1', name: 'Dr. Priya Ramesh', domain: 'AI & Data Science', experience: '8 Years', status: 'Active', examsCreated: 12, rating: '4.9/5' },
  { id: 'int_2', name: 'Prof. Rajesh Khanna', domain: 'Data Structures & Algorithms', experience: '12 Years', status: 'Active', examsCreated: 18, rating: '4.8/5' },
  { id: 'int_3', name: 'Dr. Sunita Deshmukh', domain: 'Database Systems', experience: '10 Years', status: 'Active', examsCreated: 15, rating: '4.9/5' },
  { id: 'int_4', name: 'Prof. Michael Chang', domain: 'Cyber Security', experience: '6 Years', status: 'Active', examsCreated: 8, rating: '4.7/5' },
  { id: 'int_5', name: 'Dr. Harish Kumar', domain: 'Cloud Computing', experience: '5 Years', status: 'Pending Approval', examsCreated: 2, rating: '4.5/5' },
];

export const MOCK_ADMIN_FEEDBACK = [
  {
    id: 'fb_1',
    user: 'Aarav Sharma (Student)',
    role: 'Student',
    category: 'Exam Interface',
    rating: 5,
    message: 'The AI proctoring checks before starting the exam were smooth and transparent. Timer and question palette made navigation seamless.',
    date: '2026-08-06',
    status: 'Resolved',
  },
  {
    id: 'fb_2',
    user: 'Dr. Priya Ramesh (Interviewer)',
    role: 'Interviewer',
    category: 'Question Upload',
    rating: 5,
    message: 'PDF upload feature works fast. Converting syllabus notes into MCQs saves hours of manual question drafting.',
    date: '2026-08-05',
    status: 'Reviewed',
  },
  {
    id: 'fb_3',
    user: 'Rohan Mehta (Student)',
    role: 'Student',
    category: 'Proctoring Warning',
    rating: 4,
    message: 'Accidentally moved my cursor out of full screen and got a prompt warning. Clear guidance helped me stay on screen.',
    date: '2026-08-04',
    status: 'Resolved',
  },
];

export const MOCK_GRAPH_DATA = {
  studentPerformance: [
    { subject: 'Data Structures', avgScore: 84, topScore: 98, passRate: 94 },
    { subject: 'Machine Learning', avgScore: 78, topScore: 96, passRate: 88 },
    { subject: 'Database Systems', avgScore: 86, topScore: 100, passRate: 96 },
    { subject: 'Computer Networks', avgScore: 80, topScore: 94, passRate: 90 },
    { subject: 'Cyber Security', avgScore: 75, topScore: 92, passRate: 85 },
    { subject: 'Web Architecture', avgScore: 88, topScore: 99, passRate: 97 },
  ],
  systemUsage: [
    { month: 'Jan', examsConducted: 420, activeStudents: 2800, proctorFlags: 18 },
    { month: 'Feb', examsConducted: 680, activeStudents: 3400, proctorFlags: 24 },
    { month: 'Mar', examsConducted: 950, activeStudents: 4100, proctorFlags: 19 },
    { month: 'Apr', examsConducted: 1200, activeStudents: 4900, proctorFlags: 22 },
    { month: 'May', examsConducted: 1450, activeStudents: 5600, proctorFlags: 15 },
    { month: 'Jun', examsConducted: 1890, activeStudents: 6400, proctorFlags: 12 },
    { month: 'Jul', examsConducted: 2200, activeStudents: 7200, proctorFlags: 14 },
  ],
  proctoringDistribution: [
    { name: 'Clean Sessions', value: 92, fill: '#10B981' },
    { name: 'Tab Switch Warnings', value: 5, fill: '#F59E0B' },
    { name: 'Multi-Person Alerts', value: 2, fill: '#EF4444' },
    { name: 'Audio/Mic Activity', value: 1, fill: '#6366F1' },
  ],
};
